# Generated by Django 4.0.2 on 2022-02-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Countries', models.CharField(max_length=100)),
                ('Confirmed', models.CharField(max_length=100)),
                ('Recovered', models.CharField(max_length=100)),
                ('Deaths', models.CharField(max_length=100)),
                ('Active_today', models.CharField(max_length=100)),
                ('Death_today', models.CharField(max_length=100)),
                ('Recovered_today', models.CharField(max_length=100)),
            ],
        ),
    ]
