# Generated by Django 4.0.2 on 2022-02-12 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_asia_omnicr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asia',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 2, 12), max_length=100),
        ),
        migrations.AddField(
            model_name='asia',
            name='Time',
            field=models.TimeField(default=datetime.time(13, 33, 18, 342576)),
        ),
    ]
