# Generated by Django 4.0.2 on 2022-02-12 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_asia_omnicr', '0003_alter_asia_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CumulativeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Confirmed', models.CharField(max_length=100)),
                ('Recovered', models.CharField(max_length=100)),
                ('Deaths', models.CharField(max_length=100)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covid_asia_omnicr.countries')),
            ],
        ),
        migrations.CreateModel(
            name='DeltaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2022, 2, 12), max_length=100)),
                ('Time', models.TimeField(default=datetime.time(14, 58, 45, 488144))),
                ('Active', models.CharField(default='0', max_length=100)),
                ('Death', models.CharField(default='0', max_length=100)),
                ('Recovered', models.CharField(default='0', max_length=100)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covid_asia_omnicr.countries')),
            ],
        ),
        migrations.DeleteModel(
            name='Asia',
        ),
    ]
