# Generated by Django 4.0.2 on 2022-02-12 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_asia_omnicr', '0004_countries_cumulativestats_deltastats_delete_asia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltastats',
            name='Time',
            field=models.TimeField(default=datetime.time(18, 57, 29, 793481)),
        ),
    ]
