# Generated by Django 4.0.2 on 2022-02-12 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_asia_omnicr', '0005_alter_deltastats_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumulativestats',
            name='id',
        ),
        migrations.RemoveField(
            model_name='deltastats',
            name='id',
        ),
        migrations.AlterField(
            model_name='cumulativestats',
            name='aid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deltastats',
            name='Time',
            field=models.TimeField(default=datetime.time(22, 40, 55, 565735)),
        ),
        migrations.AlterField(
            model_name='deltastats',
            name='aid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
