# Generated by Django 4.0.2 on 2022-02-13 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_asia_omnicr', '0006_remove_cumulativestats_id_remove_deltastats_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumulativestats',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='deltastats',
            name='aid',
        ),
        migrations.AddField(
            model_name='cumulativestats',
            name='Country',
            field=models.CharField(default='Not Available', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cumulativestats',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deltastats',
            name='Country',
            field=models.CharField(default='Not Available', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deltastats',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countries',
            name='Country',
            field=models.CharField(default='Not Available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='aid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deltastats',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 2, 13), max_length=100),
        ),
        migrations.AlterField(
            model_name='deltastats',
            name='Time',
            field=models.TimeField(default=datetime.time(13, 9, 2, 717717)),
        ),
    ]
