# Generated by Django 4.0.2 on 2022-02-13 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_asia_omnicr', '0007_remove_cumulativestats_aid_remove_deltastats_aid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltastats',
            name='Time',
            field=models.TimeField(default=datetime.time(13, 10, 12, 144814)),
        ),
    ]
