# Generated by Django 4.0.2 on 2022-02-13 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_asia_omnicr', '0009_remove_cumulativestats_id_cumulativestats_aid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltastats',
            name='Time',
            field=models.TimeField(default=datetime.time(14, 30, 17, 493664)),
        ),
    ]
